version: '3.5'

services:
  app_test:
      container_name: ${CONTAINER_NAME}.app_test
      build:
        context: .
        target: installer
      command: ["npm", "test"]
      volumes:
        - ./src:/install/src
        - ./.env_test:/install/.env
        - ./tsconfig.json:/install/tsconfig.json
        - ./package.json:/install/package.json
        - ./logs:/install/logs
      networks:
        - addressbook-backend-test
      environment:
        - NODE_ENV=test
      depends_on:
        - mongodb_test
      tty: true

  mongodb_test:
    container_name: ${CONTAINER_NAME}.mongodb_test
    image: mongo
    volumes:
      - mongodbTest:/data/db
    networks:
      - addressbook-backend-test
    expose:
      - 27017

#  firebase_test:
#    container_name: ${CONTAINER_NAME}.firebase_test
#    build: ./docker/firebase
#    volumes:
#      - ./docker/firebase/server.js:/app/server.js
#    networks:
#      - addressbook-backend-test
#    environment:
#      - FIREBASE_TEST_URL=${FIREBASE_TEST_URL}
#      - FIREBASE_TEST_PORT=${FIREBASE_TEST_PORT}

volumes:
  mongodbTest:

networks:
  addressbook-backend-test:
