version: '3'

services:
  app:
      container_name: ${CONTAINER_NAME}.app
      build: .
      command: ["npm", "start"]
      volumes:
        - .:/usr/src/app
      networks:
        - addressbook-backend
      environment:
        - NODE_ENV=${NODE_ENV}
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
      restart: always
      depends_on:
        - mongodb

  mongodb:
    container_name: ${CONTAINER_NAME}.mongodb
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - addressbook-backend
    restart: always

volumes:
  mongodb:

networks:
  addressbook-backend:
