version: '3'

services:
  app:
      container_name: ${CONTAINER_NAME}.app
      image: node
      working_dir: /app
      command: ["npm", "start"]
      volumes:
        - .:/app
      networks:
        - addressbook-backend
      environment:
        - NODE_ENV=${NODE_ENV}
      ports:
        - ${PORT}:${PORT}
      depends_on:
        - mongodb

  mongodb:
    container_name: ${CONTAINER_NAME}.mongodb
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - addressbook-backend

volumes:
  mongodb:

networks:
  addressbook-backend:
